server:
  port: 80

logging:
  level:
    root: info

spring:
  jackson:
    property-naming-strategy: UPPER_CAMEL_CASE

wopi:
  owa_url: http://192.168.56.105
  check_file_info_url: http://192.168.199.209/wopi/files
  docs_dir: e:/docs
