server:
  port: 80

logging:
  level:
    root: info

spring:
  jackson:
    property-naming-strategy: UPPER_CAMEL_CASE

wopi:
  owa:
    uri: http://192.168.56.105
  file-info:
    uri: http://192.168.199.209/wopi/files
  docs:
    uri: e:/docs